package com.security.stealthapp.ui.theme

import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

enum class AppLanguage(val nativeName: String) {
    ENGLISH("English"),
    DARI("دری"),
    PASHTO("پښتو")
}

fun AppLanguage.layoutDirection(): LayoutDirection =
    if (this == AppLanguage.ENGLISH) LayoutDirection.Ltr else LayoutDirection.Rtl

data class AppStrings(
    // Top-bar taglines
    val taglineCustomer: String,
    val taglineProvider: String,
    val taglineAdmin: String,
    val taglineRegister: String,
    // Category chips (display labels parallel to internal English keys)
    val categoryAll: String,
    val categoryHair: String,
    val categoryMakeup: String,
    val categoryNails: String,
    val categorySkincare: String,
    val categoryEyebrows: String,
    // Neighborhood labels (parallel to internal English keys)
    val neighborhoodAll: String,
    val neighborhood1: String,
    val neighborhood3: String,
    val neighborhood6: String,
    val neighborhood9: String,
    val neighborhood11: String,
    val neighborhood13: String,
    // Salon card
    val availableNow: String,
    val notAvailable: String,
    val book: String,
    val providersFound: (Int) -> String,
    val noProvidersTitle: String,
    val noProvidersSubtext: String,
    // Booking flow
    val myBookings: String,
    val chooseService: String,
    val cancel: String,
    val next: String,
    val selectTime: String,
    val confirmBooking: String,
    val bookingRequestSent: String,
    val bookingConfirmText: (String) -> String,
    val ok: String,
    val noBookingsTitle: String,
    val noBookingsSubtext: String,
    val close: String,
    // Provider dashboard
    val acceptingBookings: String,
    val closedForBookings: String,
    val customersCanSeeYou: String,
    val youAreHidden: String,
    val tabRequests: String,
    val tabMyProfile: String,
    val noPendingRequests: String,
    val noPendingRequestsSubtext: String,
    val requestedAt: String,
    val accept: String,
    val decline: String,
    val sectionLocation: String,
    val sectionServices: String,
    val districtArea: String,
    val addServiceLabel: String,
    val addServiceHint: String,
    val noServicesAdded: String,
    val saveProfile: String,
    val profileSavedTitle: String,
    val profileSavedText: String,
    // Register screen
    val createAccount: String,
    val taglineSecure: String,
    val sectionPersonalInfo: String,
    val sectionSalonDetails: String,
    val roleProvider: String,
    val roleCustomer: String,
    val roleProviderDesc: String,
    val roleCustomerDesc: String,
    val fullName: String,
    val phoneNumber: String,
    val secretPin: String,
    val confirmPin: String,
    val salonName: String,
    val addServiceExample: String,
    val creatingAccount: String,
    val welcomeTitle: (String) -> String,
    val accountReadyText: String,
    val goToApp: String,
    val registrationSubmittedTitle: String,
    val salonUnderReviewText: String,
    val gotIt: String,
    val pleaseCheckTitle: String,
    // Admin dashboard
    val adminPanelTitle: String,
    val approvalQueueSubtitle: String,
    val noPendingAppsTitle: String,
    val noPendingAppsSubtext: String,
    val approve: String,
    val reject: String,
    val pending: String,
    // Chat
    val chat: String,
    val messagePlaceholder: String,
    val send: String,
    // Offline / status
    val offlineBanner: String,
    val bookingUpdatedTitle: String,
    val bookingConfirmedText: (String) -> String,
    val bookingDeclinedText: (String) -> String,
    // Appointment reminders
    val reminderTitle: String,
    val remindedTomorrow: (String) -> String,
    val remindedInHour: (String) -> String,
    // Customer booking cancellation
    val cancelAppointment: String,
    val cancelConfirmTitle: String,
    val cancelConfirmText: String,
    // Provider analytics
    val tabAnalytics: String,
    val analyticsTotal: String,
    val analyticsConfirmed: String,
    val analyticsCancelled: String,
    val analyticsByService: String,
    val noDataYet: String,
    // Ratings & reviews
    val leaveReview: String,
    val rateExperience: String,
    val reviewCommentHint: String,
    val submit: String,
    val reviewThanks: String,
    val reviews: String,
    val noReviewsYet: String,
    // Favorites
    val favorites: String,
    val noFavoritesTitle: String,
    val noFavoritesSubtext: String,
    // Reschedule
    val reschedule: String,
    val rescheduleTitle: String,
    // Common
    val lock: String,
    val languagePickerTitle: String,
)

object StringResources {

    val ENGLISH = AppStrings(
        taglineCustomer            = "Private · Discreet · Trusted",
        taglineProvider            = "Provider · Private · Discreet",
        taglineAdmin               = "Provider approval queue",
        taglineRegister            = "Private · Secure · Discreet",
        categoryAll                = "All",
        categoryHair               = "Hair",
        categoryMakeup             = "Makeup",
        categoryNails              = "Nails",
        categorySkincare           = "Skincare",
        categoryEyebrows           = "Eyebrows",
        neighborhoodAll            = "All Neighborhoods",
        neighborhood1              = "District 1 – Kabul Center",
        neighborhood3              = "District 3 – Khair Khana",
        neighborhood6              = "District 6 – Karte Seh",
        neighborhood9              = "District 9 – Dasht-e Barchi",
        neighborhood11             = "District 11 – Qala-e Wahed",
        neighborhood13             = "District 13 – Afshar",
        availableNow               = "Available now",
        notAvailable               = "Not available",
        book                       = "Book",
        providersFound             = { n -> "$n provider${if (n == 1) "" else "s"} found" },
        noProvidersTitle           = "No providers found",
        noProvidersSubtext         = "Try a different category or neighborhood,\nor check back later.",
        myBookings                 = "My Bookings",
        chooseService              = "Choose a service",
        cancel                     = "Cancel",
        next                       = "Next →",
        selectTime                 = "Select time",
        confirmBooking             = "Confirm booking",
        bookingRequestSent         = "Booking Request Sent",
        bookingConfirmText         = { name -> "Request sent to $name. She will contact you discreetly." },
        ok                         = "OK",
        noBookingsTitle            = "No bookings yet.",
        noBookingsSubtext          = "Find a provider and tap Book to get started.",
        close                      = "Close",
        acceptingBookings          = "Accepting Bookings",
        closedForBookings          = "Closed for Bookings",
        customersCanSeeYou         = "Customers can see and book you",
        youAreHidden               = "You are hidden from customers",
        tabRequests                = "Requests",
        tabMyProfile               = "My Profile",
        noPendingRequests          = "No pending requests",
        noPendingRequestsSubtext   = "New booking requests from customers\nwill appear here.",
        requestedAt                = "Requested:",
        accept                     = "Accept",
        decline                    = "Decline",
        sectionLocation            = "Location",
        sectionServices            = "Services Offered",
        districtArea               = "District / Area",
        addServiceLabel            = "Add service…",
        addServiceHint             = "Add a service (e.g. Hair)",
        noServicesAdded            = "No services added yet.",
        saveProfile                = "Save Profile",
        profileSavedTitle          = "Profile Saved",
        profileSavedText           = "Your salon details have been updated.",
        createAccount              = "Create Account",
        taglineSecure              = "Private · Secure · Discreet",
        sectionPersonalInfo        = "Personal Information",
        sectionSalonDetails        = "Salon Details",
        roleProvider               = "Service Provider",
        roleCustomer               = "Customer",
        roleProviderDesc           = "Register your salon — pending admin approval",
        roleCustomerDesc           = "Find and book beauty services",
        fullName                   = "Full Name",
        phoneNumber                = "Phone Number",
        secretPin                  = "Secret PIN (4+ digits)",
        confirmPin                 = "Confirm PIN",
        salonName                  = "Salon Name",
        addServiceExample          = "Add a service (e.g. Hair)",
        creatingAccount            = "Creating account…",
        welcomeTitle               = { name -> "Welcome, $name!" },
        accountReadyText           = "Your account is ready. Return to the notepad and enter your PIN to sign in.",
        goToApp                    = "Go to app",
        registrationSubmittedTitle = "Registration Submitted",
        salonUnderReviewText       = "Your salon is under review. Once approved by our team, your PIN will activate and you can sign in.",
        gotIt                      = "Got it",
        pleaseCheckTitle           = "Please check your details",
        adminPanelTitle            = "Admin Panel",
        approvalQueueSubtitle      = "Provider approval queue",
        noPendingAppsTitle         = "No pending applications",
        noPendingAppsSubtext       = "New provider registrations\nwill appear here for approval.",
        approve                    = "Approve",
        reject                     = "Reject",
        pending                    = "Pending",
        chat                       = "Chat",
        messagePlaceholder         = "Type a message…",
        send                       = "Send",
        offlineBanner              = "You're offline — showing cached results",
        bookingUpdatedTitle        = "Booking Update",
        bookingConfirmedText       = { name -> "$name confirmed your appointment!" },
        bookingDeclinedText        = { name -> "$name has declined your appointment." },
        reminderTitle              = "Appointment Reminder",
        remindedTomorrow           = { name -> "Your appointment at $name is tomorrow." },
        remindedInHour             = { name -> "Your appointment at $name starts in 1 hour." },
        cancelAppointment          = "Cancel Appointment",
        cancelConfirmTitle         = "Cancel this booking?",
        cancelConfirmText          = "This will cancel your appointment. This cannot be undone.",
        tabAnalytics               = "Analytics",
        analyticsTotal             = "Total Requests",
        analyticsConfirmed         = "Confirmed",
        analyticsCancelled         = "Cancelled",
        analyticsByService         = "By Service",
        noDataYet                  = "No bookings yet",
        leaveReview                = "Leave a Review",
        rateExperience             = "Rate your experience",
        reviewCommentHint          = "Share your experience (optional)",
        submit                     = "Submit",
        reviewThanks               = "Thank you for your review!",
        reviews                    = "Reviews",
        noReviewsYet               = "No reviews yet",
        favorites                  = "Favorites",
        noFavoritesTitle           = "No favorites yet",
        noFavoritesSubtext         = "Tap the heart on a salon to save it here.",
        reschedule                 = "Reschedule",
        rescheduleTitle            = "Pick a new time",
        lock                       = "Lock",
        languagePickerTitle        = "Language / زبان / ژبه",
    )

    val DARI = AppStrings(
        taglineCustomer            = "خصوصی · مخفیانه · معتمد",
        taglineProvider            = "ارائه‌دهنده · خصوصی · مخفیانه",
        taglineAdmin               = "صف تایید ارائه‌دهندگان",
        taglineRegister            = "خصوصی · امن · مخفیانه",
        categoryAll                = "همه",
        categoryHair               = "مو",
        categoryMakeup             = "آرایش",
        categoryNails              = "ناخن",
        categorySkincare           = "مراقبت پوست",
        categoryEyebrows           = "ابرو",
        neighborhoodAll            = "همه محله‌ها",
        neighborhood1              = "ناحیه ۱ – مرکز کابل",
        neighborhood3              = "ناحیه ۳ – خیرخانه",
        neighborhood6              = "ناحیه ۶ – کارته سه",
        neighborhood9              = "ناحیه ۹ – دشت برچی",
        neighborhood11             = "ناحیه ۱۱ – قلعه واحد",
        neighborhood13             = "ناحیه ۱۳ – افشار",
        availableNow               = "در دسترس",
        notAvailable               = "در دسترس نیست",
        book                       = "رزرو",
        providersFound             = { n -> "$n ارائه‌دهنده پیدا شد" },
        noProvidersTitle           = "ارائه‌دهنده‌ای پیدا نشد",
        noProvidersSubtext         = "دسته‌بندی یا محله دیگری را امتحان کنید،\nیا بعداً دوباره بررسی کنید.",
        myBookings                 = "رزروهای من",
        chooseService              = "انتخاب خدمات",
        cancel                     = "لغو",
        next                       = "← بعدی",
        selectTime                 = "انتخاب زمان",
        confirmBooking             = "تایید رزرو",
        bookingRequestSent         = "درخواست رزرو ارسال شد",
        bookingConfirmText         = { name -> "درخواست به $name ارسال شد. او مخفیانه با شما تماس می‌گیرد." },
        ok                         = "تایید",
        noBookingsTitle            = "هنوز رزروی ندارید.",
        noBookingsSubtext          = "یک ارائه‌دهنده پیدا کنید و روی رزرو ضربه بزنید.",
        close                      = "بستن",
        acceptingBookings          = "در حال پذیرش رزرو",
        closedForBookings          = "بسته برای رزرو",
        customersCanSeeYou         = "مشتریان می‌توانند شما را ببینند و رزرو کنند",
        youAreHidden               = "از دید مشتریان پنهان هستید",
        tabRequests                = "درخواست‌ها",
        tabMyProfile               = "پروفایل من",
        noPendingRequests          = "درخواست معلقی وجود ندارد",
        noPendingRequestsSubtext   = "درخواست‌های رزرو جدید از مشتریان\nاینجا نمایش داده می‌شود.",
        requestedAt                = "درخواست:",
        accept                     = "قبول",
        decline                    = "رد",
        sectionLocation            = "مکان",
        sectionServices            = "خدمات ارائه شده",
        districtArea               = "ناحیه / منطقه",
        addServiceLabel            = "افزودن خدمت…",
        addServiceHint             = "افزودن خدمت (مثلاً مو)",
        noServicesAdded            = "هنوز خدماتی اضافه نشده.",
        saveProfile                = "ذخیره پروفایل",
        profileSavedTitle          = "پروفایل ذخیره شد",
        profileSavedText           = "اطلاعات سالن شما به‌روزرسانی شد.",
        createAccount              = "ایجاد حساب",
        taglineSecure              = "خصوصی · امن · مخفیانه",
        sectionPersonalInfo        = "اطلاعات شخصی",
        sectionSalonDetails        = "جزئیات سالن",
        roleProvider               = "ارائه‌دهنده خدمات",
        roleCustomer               = "مشتری",
        roleProviderDesc           = "سالن خود را ثبت کنید — در انتظار تایید مدیر",
        roleCustomerDesc           = "خدمات زیبایی را پیدا کنید و رزرو کنید",
        fullName                   = "نام کامل",
        phoneNumber                = "شماره تلفن",
        secretPin                  = "رمز پین محرمانه (۴+ رقم)",
        confirmPin                 = "تایید پین",
        salonName                  = "نام سالن",
        addServiceExample          = "افزودن خدمت (مثلاً مو)",
        creatingAccount            = "در حال ایجاد حساب…",
        welcomeTitle               = { name -> "خوش آمدید، $name!" },
        accountReadyText           = "حساب شما آماده است. به دفترچه برگردید و پین خود را وارد کنید.",
        goToApp                    = "رفتن به برنامه",
        registrationSubmittedTitle = "ثبت‌نام ارسال شد",
        salonUnderReviewText       = "سالن شما در حال بررسی است. پس از تایید توسط تیم ما، پین شما فعال می‌شود.",
        gotIt                      = "متوجه شدم",
        pleaseCheckTitle           = "لطفاً جزئیات را بررسی کنید",
        adminPanelTitle            = "پنل مدیریت",
        approvalQueueSubtitle      = "صف تایید ارائه‌دهندگان",
        noPendingAppsTitle         = "درخواست معلقی وجود ندارد",
        noPendingAppsSubtext       = "ثبت‌نام‌های ارائه‌دهنده جدید\nاینجا برای تایید نمایش داده می‌شود.",
        approve                    = "تایید",
        reject                     = "رد",
        pending                    = "معلق",
        chat                       = "گفتگو",
        messagePlaceholder         = "پیام بنویسید…",
        send                       = "ارسال",
        offlineBanner              = "آفلاین هستید — نتایج ذخیره‌شده نمایش داده می‌شود",
        bookingUpdatedTitle        = "به‌روزرسانی رزرو",
        bookingConfirmedText       = { name -> "$name رزرو شما را تایید کرد!" },
        bookingDeclinedText        = { name -> "$name رزرو شما را رد کرد." },
        reminderTitle              = "یادآوری قرار ملاقات",
        remindedTomorrow           = { name -> "قرار ملاقات شما در $name فردا است." },
        remindedInHour             = { name -> "قرار ملاقات شما در $name یک ساعت دیگر شروع می‌شود." },
        cancelAppointment          = "لغو رزرو",
        cancelConfirmTitle         = "لغو این رزرو؟",
        cancelConfirmText          = "این رزرو را لغو می‌کند. این عملیات قابل بازگشت نیست.",
        tabAnalytics               = "آمار",
        analyticsTotal             = "کل درخواست‌ها",
        analyticsConfirmed         = "تایید شده",
        analyticsCancelled         = "لغو شده",
        analyticsByService         = "بر اساس خدمات",
        noDataYet                  = "هنوز رزروی نیست",
        leaveReview                = "ثبت نظر",
        rateExperience             = "تجربه خود را امتیاز دهید",
        reviewCommentHint          = "تجربه خود را بنویسید (اختیاری)",
        submit                     = "ثبت",
        reviewThanks               = "از نظر شما متشکریم!",
        reviews                    = "نظرات",
        noReviewsYet               = "هنوز نظری نیست",
        favorites                  = "علاقه‌مندی‌ها",
        noFavoritesTitle           = "هنوز علاقه‌مندی ندارید",
        noFavoritesSubtext         = "برای ذخیره، روی قلب یک سالن ضربه بزنید.",
        reschedule                 = "تغییر زمان",
        rescheduleTitle            = "زمان جدید را انتخاب کنید",
        lock                       = "قفل",
        languagePickerTitle        = "Language / زبان / ژبه",
    )

    val PASHTO = AppStrings(
        taglineCustomer            = "شخصي · پټ · باوروړ",
        taglineProvider            = "چمتو کوونکی · شخصي · پټ",
        taglineAdmin               = "د چمتو کوونکو د تایید کتار",
        taglineRegister            = "شخصي · خوندي · پټ",
        categoryAll                = "ټول",
        categoryHair               = "ویښتان",
        categoryMakeup             = "سینګار",
        categoryNails              = "نوکان",
        categorySkincare           = "جلدي پاملرنه",
        categoryEyebrows           = "وروځې",
        neighborhoodAll            = "ټول ګاونډونه",
        neighborhood1              = "ناحیه ۱ – د کابل مرکز",
        neighborhood3              = "ناحیه ۳ – خیرخانه",
        neighborhood6              = "ناحیه ۶ – کارته سه",
        neighborhood9              = "ناحیه ۹ – دشت برچي",
        neighborhood11             = "ناحیه ۱۱ – قلعه واحد",
        neighborhood13             = "ناحیه ۱۳ – افشار",
        availableNow               = "اوس شتون لري",
        notAvailable               = "شتون نه لري",
        book                       = "وخت اخیستل",
        providersFound             = { n -> "$n چمتو کوونکي وموندل شول" },
        noProvidersTitle           = "هیڅ چمتو کوونکی ونه موندل شو",
        noProvidersSubtext         = "د بل کټګورۍ یا ګاونډ هڅه وکړئ،\nیا وروسته بیا وګورئ.",
        myBookings                 = "اخیستل شوي وختونه",
        chooseService              = "خدمت غوره کړئ",
        cancel                     = "شا کول",
        next                       = "← بل",
        selectTime                 = "وخت وټاکئ",
        confirmBooking             = "د بکینګ تایید",
        bookingRequestSent         = "د بکینګ غوښتنه واستول شوه",
        bookingConfirmText         = { name -> "غوښتنه $name ته واستول شوه. هغه به له تاسو سره پټ اړیکه وکړي." },
        ok                         = "سمه ده",
        noBookingsTitle            = "لا هیڅ بکینګ نشته.",
        noBookingsSubtext          = "یو چمتو کوونکی ومومئ او د بک کولو تڼۍ ووهئ.",
        close                      = "بندول",
        acceptingBookings          = "بکونه منم",
        closedForBookings          = "بکونو لپاره بند",
        customersCanSeeYou         = "پیرودونکي کولی شي تاسو وګوري او بک کړي",
        youAreHidden               = "تاسو د پیرودونکو له لیده پټ یاست",
        tabRequests                = "غوښتنې",
        tabMyProfile               = "زما پروفایل",
        noPendingRequests          = "انتظار کې غوښتنه نشته",
        noPendingRequestsSubtext   = "د پیرودونکو نوې د بکینګ غوښتنې\nدلته ښکاره کیږي.",
        requestedAt                = "غوښتل شوی:",
        accept                     = "قبول",
        decline                    = "رد",
        sectionLocation            = "ځای",
        sectionServices            = "وړاندیز شوي خدمتونه",
        districtArea               = "سیمه / ناحیه",
        addServiceLabel            = "خدمت اضافه کړئ…",
        addServiceHint             = "خدمت اضافه کړئ (لکه ویښتان)",
        noServicesAdded            = "لا هیڅ خدمت اضافه نشوی.",
        saveProfile                = "پروفایل خوندي کړئ",
        profileSavedTitle          = "پروفایل خوندي شو",
        profileSavedText           = "ستاسو د سالون توضیحات تازه شول.",
        createAccount              = "حساب جوړ کړئ",
        taglineSecure              = "شخصي · خوندي · پټ",
        sectionPersonalInfo        = "شخصي معلومات",
        sectionSalonDetails        = "د سالون توضیحات",
        roleProvider               = "د خدماتو چمتو کوونکی",
        roleCustomer               = "پیرودونکی",
        roleProviderDesc           = "خپل سالون ثبت کړئ — د مدیر تایید ته انتظار",
        roleCustomerDesc           = "د ښکلا خدمتونه ومومئ او بک کړئ",
        fullName                   = "بشپړ نوم",
        phoneNumber                = "د تلیفون شمیره",
        secretPin                  = "محرمانه PIN (۴+ شمیرې)",
        confirmPin                 = "PIN تایید کړئ",
        salonName                  = "د سالون نوم",
        addServiceExample          = "خدمت اضافه کړئ (لکه ویښتان)",
        creatingAccount            = "حساب جوړیږي…",
        welcomeTitle               = { name -> "ښه راغلاست، $name!" },
        accountReadyText           = "ستاسو حساب چمتو دی. نوټ پیډ ته ستانه شئ او خپل PIN دننه کړئ.",
        goToApp                    = "اپ ته لاړ شئ",
        registrationSubmittedTitle = "ثبتنام وسپارل شو",
        salonUnderReviewText       = "ستاسو سالون د بیاکتنې لاندې دی. د تایید وروسته، ستاسو PIN فعالیږي.",
        gotIt                      = "پوه شوم",
        pleaseCheckTitle           = "مهرباني وکړئ خپل توضیحات وګورئ",
        adminPanelTitle            = "داشبور",
        approvalQueueSubtitle      = "د چمتو کوونکو د تایید کتار",
        noPendingAppsTitle         = "انتظار کې څوک نشته",
        noPendingAppsSubtext       = "د چمتو کوونکو نوي ثبتنامونه\nدلته د تایید لپاره ښکاره کیږي.",
        approve                    = "تایید",
        reject                     = "رد",
        pending                    = "انتظار",
        chat                       = "خبرې",
        messagePlaceholder         = "پیغام ولیکئ…",
        send                       = "واستول",
        offlineBanner              = "آفلاین یاست — خوندي شوي پایلې ښودل کیږي",
        bookingUpdatedTitle        = "د بکینګ تازه خبر",
        bookingConfirmedText       = { name -> "$name ستاسو بکینګ تایید کړ!" },
        bookingDeclinedText        = { name -> "$name ستاسو بکینګ رد کړ." },
        reminderTitle              = "د ملاقات یادونه",
        remindedTomorrow           = { name -> "ستاسو ملاقات $name کې سبا دی." },
        remindedInHour             = { name -> "ستاسو ملاقات $name کې یو ساعت وروسته پیلیږي." },
        cancelAppointment          = "بکینګ لغو کول",
        cancelConfirmTitle         = "دا بکینګ لغو کړئ؟",
        cancelConfirmText          = "دا به ستاسو ملاقات لغو کړي. دا عملیه بیرته نه راتلی شي.",
        tabAnalytics               = "احصایه",
        analyticsTotal             = "ټول غوښتنې",
        analyticsConfirmed         = "تایید شوي",
        analyticsCancelled         = "لغو شوي",
        analyticsByService         = "د خدمت له مخې",
        noDataYet                  = "لا هیڅ بکینګ نشته",
        leaveReview                = "نظر ورکول",
        rateExperience             = "خپلې تجربې ته نمره ورکړئ",
        reviewCommentHint          = "خپله تجربه ولیکئ (اختیاري)",
        submit                     = "ثبت",
        reviewThanks               = "ستاسو د نظر څخه مننه!",
        reviews                    = "نظرونه",
        noReviewsYet               = "لا هیڅ نظر نشته",
        favorites                  = "خوښې",
        noFavoritesTitle           = "لا هیڅ خوښه نشته",
        noFavoritesSubtext         = "د خوندي کولو لپاره د سالون په زړه ووهئ.",
        reschedule                 = "وخت بدلول",
        rescheduleTitle            = "نوی وخت وټاکئ",
        lock                       = "قفل",
        languagePickerTitle        = "Language / زبان / ژبه",
    )

    fun forLanguage(lang: AppLanguage): AppStrings = when (lang) {
        AppLanguage.ENGLISH -> ENGLISH
        AppLanguage.DARI    -> DARI
        AppLanguage.PASHTO  -> PASHTO
    }
}

val LocalStrings = compositionLocalOf { StringResources.ENGLISH }
